name: flowsense
version: '1.0'
main: id.flowsense.Main
api-version: '1.18'
commands:
  flowsense:
    description: Main command for FlowSense
    usage: /flowsense <reload|lookup>
authors: [ Sattr ]
description: Webhook-powered donation notifier for Minecraft
website: https://sattr.vercel.id
